services:
  - type: web
    name: tyler-durden-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && cd webapp"
    startCommand: "cd webapp && gunicorn app:app"
    branch: main
